<?php

declare(strict_types=1);

namespace Test\Web;

use Phant\DataStructure\Web\EmailAttachment;

final class EmailAttachmentTest extends \PHPUnit\Framework\TestCase
{
    public const Content = 'JVBERi0xLjcNCiXi48/TDQozIDAgb2JqDQo8PA0KL0xpbmVhcml6ZWQgMQ0KL0wgMTYzMA0KL0ggWyA2MjAgMTIyIF0NCi9PIDUNCi9FIDEyMTcNCi9OIDENCi9UIDE0NDQNCj4+DQplbmRvYmoNCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICANCnhyZWYNCjMgNQ0KMDAwMDAwMDAxNyAwMDAwMCBuDQowMDAwMDAwNTY1IDAwMDAwIG4NCjAwMDAwMDA3NDIgMDAwMDAgbg0KMDAwMDAwMDg5NCAwMDAwMCBuDQowMDAwMDAwNjIwIDAwMDAwIG4NCnRyYWlsZXINCjw8DQovU2l6ZSA4DQovUHJldiAxNDM0DQovSW5mbyAyIDAgUg0KL1Jvb3QgNCAwIFINCi9JRCBbPGQyMjc5OTNkMzg3N2EwZDA5MTgzYWRhN2FjZWFkZDEwPjxkMjI3OTkzZDM4NzdhMGQwOTE4M2FkYTdhY2VhZGQxMD5dDQo+Pg0Kc3RhcnR4cmVmDQowDQolJUVPRg0KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICANCjQgMCBvYmoNCjw8DQovVHlwZSAvQ2F0YWxvZw0KL1BhZ2VzIDEgMCBSDQo+Pg0KZW5kb2JqDQo3IDAgb2JqDQo8PA0KL1MgMzYNCi9GaWx0ZXIgL0ZsYXRlRGVjb2RlDQovTGVuZ3RoIDM1DQo+Pg0Kc3RyZWFtDQp4nGNgYGACohwGIGC8zYANcCCxmaCYgWEGUHw1AwBJ4AKkCg0KZW5kc3RyZWFtDQplbmRvYmoNCjUgMCBvYmoNCjw8DQovVHlwZSAvUGFnZQ0KL01lZGlhQm94IFsgMCAwIDUwMCA1MDAgXQ0KL1Jlc291cmNlcyA8PCA+Pg0KL0NvbnRlbnRzIDYgMCBSDQovUGFyZW50IDEgMCBSDQovUm90YXRlIDANCi9Dcm9wQm94IFsgMCAwIDUwMCA1MDAgXQ0KPj4NCmVuZG9iag0KNiAwIG9iag0KPDwNCi9GaWx0ZXIgL0ZsYXRlRGVjb2RlDQovTGVuZ3RoIDI0Mg0KPj4NCnN0cmVhbQ0KeJyNkkuOwzAIhvc+BRcYBBhsOMacodK0i3TRuf9isNM8KlWaxrJjE+AjP34UhjF+r4XAiOBexjrmMnfjva2r9VZ+ynd5FEKBbWY4w3DLXI1RohkFCBlS725wuRfRiqyVWoNBIRBVDBG2nfDi8i9IBkhEWbKwQchQNK6dHThzt4jefKJOx8H6IqR8Jvl90Cd/mdSZpvKAe6AYS3RwxzDtvU70cVpOPs8KyF+sZ98P+KyecrVuMQrI4tnJuz7l1YauYey7vGePA7D3f9e1GqqYUQcJxSrBrc4OGuYNqEf1uvZxNWfTTtrmt+VdwMb9A1KWezgNCmVuZHN0cmVhbQ0KZW5kb2JqDQoxIDAgb2JqDQo8PA0KL1R5cGUgL1BhZ2VzDQovS2lkcyBbIDUgMCBSIF0NCi9Db3VudCAxDQo+Pg0KZW5kb2JqDQoyIDAgb2JqDQo8PA0KL01vZERhdGUgKEQ6MjAyMzEyMDQwODU2MDIrMDEnMDAnKQ0KL1Byb2R1Y2VyDQooMy1IZWlnaHRzXChUTVwpIFBERiBPcHRpbWl6YXRpb24gU2hlbGwgNS45LjEuNSBcKGh0dHA6Ly93d3cucGRmLXRvb2xzLmNvbVwpKQ0KPj4NCmVuZG9iag0KeHJlZg0KMCAzDQowMDAwMDAwMDAwIDY1NTM1IGYNCjAwMDAwMDEyMTcgMDAwMDAgbg0KMDAwMDAwMTI4MyAwMDAwMCBuDQp0cmFpbGVyDQo8PA0KL1NpemUgMw0KL0lEIFs8ZDIyNzk5M2QzODc3YTBkMDkxODNhZGE3YWNlYWRkMTA+PGQyMjc5OTNkMzg3N2EwZDA5MTgzYWRhN2FjZWFkZDEwPl0NCj4+DQpzdGFydHhyZWYNCjE3OA0KJSVFT0YNCg==';

    public function testInterface(): void
    {
        $email = new EmailAttachment(
            'file.pdf',
            self::Content,
            'application/pdf'
        );

        $this->assertIsString($email->name);
        $this->assertEquals('file.pdf', $email->name);

        $this->assertIsString($email->content);
        $this->assertEquals(self::Content, $email->content);

        $this->assertIsString($email->type);
        $this->assertEquals('application/pdf', $email->type);
    }
}
